name: memo4me
services:
  api:
    build:
      context: ../../App/
      dockerfile: devops/API.Dockerfile
    ports:
      - "8002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: memo4me-api
    depends_on:
      - db
      - keycloak

  ui:
    build:
      context: ../../App/
      dockerfile: devops/UI.Dockerfile
    ports:
      - "5101:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OIDC_AUTHORITY=http://host.docker.internal:7270/realms/MemoRealm
      - OIDC_METADATA_ADDRESS=http://host.docker.internal:7270/realms/MemoRealm/.well-known/openid-configuration
      - OIDC_CLIENT_SECRET=your-client-secret
    container_name: memo4me-ui
  
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: MemoDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: memo4me-db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "7270:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak-setup/identity:/opt/keycloak/data
    command: ["start-dev"]
    restart: unless-stopped
    container_name: memo4me-keycloak

volumes:
  postgres_data:
  keycloak_data: